version: '3'

services:
  nginx:
    build: nginx/
    ports:
      # The HTTP port
      - "80:80"
    volumes: 
      - ./static:/static/
    depends_on:
      - web
    
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypass
      POSTGRES_DATABASE: db
    volumes:
      - /var/lib/yura.cc/pg_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn --bind=0.0.0.0 djangocv.wsgi
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db


