# Generated by Django 3.0.4 on 2020-04-13 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('information', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=50)),
                ('github', models.URLField(default='')),
                ('linkedin', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(default=0)),
                ('end_year', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('cv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.Cv')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('experience', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cv.Experience')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.Organization'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(default=0)),
                ('end_year', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('cv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.Cv')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='technologies',
            field=models.ManyToManyField(to='cv.Technologies'),
        ),
    ]
