# Generated by Django 3.0.4 on 2020-04-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
