# Generated by Django 3.0.3 on 2020-03-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cv_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='github',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='cv',
            name='linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
