# Generated by Django 3.0.3 on 2020-03-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200304_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
