# Generated by Django 3.0.4 on 2020-04-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200409_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cv',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cv.Cv'),
        ),
    ]
