# Generated by Django 3.0.3 on 2020-03-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20200305_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(default=0)),
                ('end_year', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.ManyToManyField(to='cv.Education'),
        ),
    ]
