# Generated by Django 3.0.4 on 2020-04-09 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='website',
        ),
        migrations.RemoveField(
            model_name='education',
            name='organization',
        ),
        migrations.AlterField(
            model_name='education',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.Cv'),
        ),
        migrations.AlterField(
            model_name='education',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.Organization'),
        ),
    ]
