# Generated by Django 3.0.3 on 2020-03-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20200305_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(default=0)),
                ('end_year', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('website', models.URLField(default='')),
                ('experience_points', models.ManyToManyField(to='cv.Points')),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.ManyToManyField(to='cv.Experience'),
        ),
    ]
