# Generated by Django 3.0.3 on 2020-03-09 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20200306_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experience_points',
        ),
        migrations.AddField(
            model_name='points',
            name='experience',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cv.Experience'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
