# Generated by Django 3.0.4 on 2020-04-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_auto_20200409_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='website',
        ),
    ]
